name: 'Premium plan: question ❔'
description: I'm a Premium plan user, I can't find a solution to my problem with MUI X.
title: "[question] "
labels: ['status: needs triage', 'Premium plan', 'support: commercial']
body:
  - type: markdown
    attributes:
      value: |
        Please provide a searchable summary of the issue in the title above ⬆️.

        ⚠️ **Don't use this form if the problem is [a bug](https://github.com/mui/mui-x/issues/new?assignees=&labels=status%3A+needs+triage&template=1.bug.yml) or a [feature request](https://github.com/mui/mui-x/issues/new?assignees=&labels=status%3A+needs+triage&template=2.feature.yml), use the dedicated form instead.**
  - type: input
    id: contact
    attributes:
      label: Order ID 💳
      description: The order ID of the purchased Premium plan. Community users can [learn more about support](https://mui.com/getting-started/support/) in the documentation.
      placeholder: 'e.g. 11111'
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Duplicates
      description: Please [search the history](https://github.com/mui/mui-x/issues) to see if an issue already exists for the same problem.
      options:
        - label: I have searched the existing issues
          required: true
  - type: checkboxes
    attributes:
      label: Latest version
      description: We roll bug fixes, performance enhancements, and other improvements into new releases.
      options:
        - label: I have tested the latest version
          required: true
  - type: textarea
    attributes:
      label: The problem in depth 🔍
  - type: textarea
    attributes:
      label: Your environment 🌎
      description: Run `npx @mui/envinfo` and post the results. If you encounter issues with TypeScript please include the used tsconfig.
      value: |
        <details>
          <summary>`npx @mui/envinfo`</summary>

        ```
          Don't forget to mention which browser you used.
          Output from `npx @mui/envinfo` goes here.
        ```
        </details>
